name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 // 官方要求

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod" // 使用 go.mod 文件中的 golang 版本

      - name: Build
        run: go build -v ./